# Generated by Django 3.2.6 on 2021-08-19 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientModel',
            new_name='Client',
        ),
    ]
